export const TypeIcons: Record<string, string> = {
  normal: '🌀',
  fighting: '🥊',
  flying: '🦅',
  poison: '💀',
  ground: '🌍',
  rock: '🪨',
  bug: '🐛',
  ghost: '👻',
  steel: '🛠️',
  fire: '🔥',
  water: '💧',
  grass: '🌿',
  electric: '⚡',
  psychic: '🔮',
  ice: '❄️',
  dragon: '🐉',
  dark: '🌑',
  fairy: '🧚‍♀️',
};
